### ISSUE TITLE
Python environment requires a parser library (e.g., lxml)

### ISSUE THREAD

**Issue by dknupp** [neelsomani/senator-filings#8]
I ran `pip install -r requirements.txt` to set up a new virtual environment, and this error occurred the first time I tried to execute main.py.
```
$ python main.py
[2020-05-26 12:18:06,606 INFO] Initializing client
Traceback (most recent call last):
  File "main.py", line 183, in <module>
    senator_txs = main()
  File "main.py", line 169, in main
    reports = senator_reports(client)
  File "main.py", line 71, in senator_reports
    token = _csrf(client)
  File "main.py", line 50, in _csrf
    landing_page = BeautifulSoup(landing_page_response.text, 'lxml')
  File "/tmp/dev3/lib/python3.8/site-packages/bs4/__init__.py", line 162, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Comment by neelsomani** [comment]
Merged your fix!
